# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 09:15
from __future__ import unicode_literals

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.upload_to, verbose_name='image'),
        ),
    ]
