# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 06:36
from __future__ import unicode_literals

import authentication.models
from django.db import migrations, models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170514_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='address2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='address3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=enumfields.fields.EnumField(enum=authentication.models.GenderType, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number1',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
