# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20170518_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
