# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-07 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20170518_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.CharField(default='/static/images/anonymous.png', max_length=255),
        ),
    ]
