# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-10 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20171210_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
